// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zad2Backend.API.Data;

namespace zad2Backend.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("zad2Backend.API.Models.Novinky", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("datum");

                    b.Property<string>("nazov");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.ToTable("Novinky");
                });

            modelBuilder.Entity("zad2Backend.API.Models.Terminy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("datum");

                    b.Property<string>("nazov");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.ToTable("Terminy");
                });
#pragma warning restore 612, 618
        }
    }
}
